version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  jobs:
    pre_install:
      # Export from Poetry to a requirements file including dev (docs) deps
      - pip install "poetry>=1.2" poetry-plugin-export
      - poetry --version
      - poetry export --with dev -f requirements.txt --output rtd-requirements.txt

python:
  install:
    - requirements: rtd-requirements.txt
    # Install the project itself (if needed by docs)
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub